{{- if and .Values.tls.enabled (not .Values.tls.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neuralbase.fullname" . }}-tls
  labels:
    {{- include "neuralbase.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""
{{- end }}
---
{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neuralbase.fullname" . }}-users
  labels:
    {{- include "neuralbase.labels" . | nindent 4 }}
type: Opaque
stringData:
  users.json: |
    {
      "admin": {
        "password_sha256": "REPLACE_ME",
        "roles": ["admin"]
      }
    }
{{- end }}
