// SPDX-License-Identifier: Apache-2.0
// TLS acceptor factory for NeuralBase SQL + Raft connections.
//
// TLS is compiled only when the `tls` Cargo feature is enabled AND
// the optional crates (tokio-rustls, rustls, rcgen, rustls-pemfile) are
// added to [dependencies] in Cargo.toml with `optional = true`.
//
// Environment variables (when `tls` feature is active):
//   TLS_ENABLED=1                   — enable TLS for SQL client connections
//   TLS_CERT_PATH / NEURALBASE_TLS_CERT  — path to PEM certificate chain
//   TLS_KEY_PATH  / NEURALBASE_TLS_KEY   — path to PEM private key (PKCS#8)
//   NEURALBASE_TLS_CA_CERT          — CA cert for node-to-node mTLS
//
// Why NASM is required on Windows x64:
//   Both `aws-lc-rs` and `ring` require NASM for assembly-optimised
//   crypto primitives (AES-GCM, SHA, ChaCha20).  Install NASM from
//   https://www.nasm.us/pub/nasm/releasebuilds/ and ensure it is on PATH,
//   then uncomment the TLS deps in Cargo.toml and rebuild with:
//   cargo build --features tls
//
// CONFIDENCE: raw=0.74 effective=0.70
// DEPENDS_ON: tokio-rustls, rustls, rustls-pemfile (all optional/feature-gated)
// NOTE: TLS not active in default build — see CONFIDENCE.md §"TLS gap".

// ── PEM helpers (feature = "tls") ─────────────────────────────────────────

/// Load PEM-encoded X.509 certificates from a file.
#[cfg(feature = "tls")]
pub fn load_certs(path: &str) -> std::io::Result<Vec<rustls::pki_types::CertificateDer<'static>>> {
    let file = std::fs::File::open(path)?;
    let mut reader = std::io::BufReader::new(file);
    rustls_pemfile::certs(&mut reader)
        .collect::<Result<Vec<_>, _>>()
        .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))
}

/// Load a PEM-encoded private key (PKCS#8 or RSA) from a file.
#[cfg(feature = "tls")]
pub fn load_key(path: &str) -> std::io::Result<rustls::pki_types::PrivateKeyDer<'static>> {
    let file = std::fs::File::open(path)?;
    let mut reader = std::io::BufReader::new(file);
    rustls_pemfile::private_key(&mut reader)
        .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))?
        .ok_or_else(|| {
            std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "no private key found in file",
            )
        })
}

// ── SQL client-to-node TLS acceptor ───────────────────────────────────────

/// TLS acceptor for SQL client connections.
/// Returns `None` if TLS is not requested via environment variables.
#[cfg(feature = "tls")]
pub mod acceptor {
    use rustls::ServerConfig;
    use std::sync::Arc;
    use tokio_rustls::TlsAcceptor;

    /// Build a TLS acceptor from environment variables.
    ///
    /// Returns `Some(acceptor)` when `TLS_ENABLED=1` or `TLS_CERT_PATH` is set.
    /// Returns `None` when TLS is not configured (plaintext mode).
    pub fn build_acceptor() -> std::io::Result<Option<TlsAcceptor>> {
        let enabled = std::env::var("TLS_ENABLED")
            .map(|v| v == "1")
            .unwrap_or(false);
        let cert_var = std::env::var("TLS_CERT_PATH")
            .or_else(|_| std::env::var("NEURALBASE_TLS_CERT"))
            .ok();
        let key_var = std::env::var("TLS_KEY_PATH")
            .or_else(|_| std::env::var("NEURALBASE_TLS_KEY"))
            .ok();

        if !enabled && cert_var.is_none() {
            return Ok(None); // TLS not requested — plaintext mode.
        }

        let cert_path = cert_var.unwrap_or_else(|| "certs/server.crt".to_string());
        let key_path = key_var.unwrap_or_else(|| "certs/server.key".to_string());

        let certs = crate::tls::load_certs(&cert_path)?;
        let key = crate::tls::load_key(&key_path)?;

        // rustls 0.23 requires an explicit CryptoProvider before first use.
        // install_default() is idempotent — ignore the error if already set.
        let _ = rustls::crypto::ring::default_provider().install_default();

        let config = ServerConfig::builder()
            .with_no_client_auth()
            .with_single_cert(certs, key)
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))?;

        tracing::info!(cert = %cert_path, "TLS enabled for SQL listener");
        Ok(Some(TlsAcceptor::from(Arc::new(config))))
    }
}

/// Placeholder when `tls` feature is disabled.
#[cfg(not(feature = "tls"))]
pub mod acceptor {
    /// TLS not compiled — always returns `None`.
    pub fn build_acceptor() -> Result<Option<std::convert::Infallible>, std::convert::Infallible> {
        Ok(None)
    }
}

// ── Node-to-node Raft mTLS ─────────────────────────────────────────────────

/// Mutual TLS for Raft RPC connections (node-to-node).
///
/// Uses cluster certificates generated by `make gen-cluster-certs`:
///   certs/ca.crt      — cluster CA (shared by all nodes)
///   certs/nodeN.crt   — node certificate (signed by CA)
///   certs/nodeN.key   — node private key
///
/// Environment variables:
///   NEURALBASE_TLS_CERT     — this node's certificate (default: certs/server.crt)
///   NEURALBASE_TLS_KEY      — this node's private key  (default: certs/server.key)
///   NEURALBASE_TLS_CA_CERT  — cluster CA certificate   (default: certs/ca.crt)
#[cfg(feature = "tls")]
pub mod node_tls {
    use rustls::pki_types::ServerName;
    use rustls::{ClientConfig, RootCertStore, ServerConfig};
    use std::sync::Arc;
    use tokio_rustls::{TlsAcceptor, TlsConnector};

    fn cert_path() -> String {
        std::env::var("NEURALBASE_TLS_CERT").unwrap_or_else(|_| "certs/server.crt".to_string())
    }
    fn key_path() -> String {
        std::env::var("NEURALBASE_TLS_KEY").unwrap_or_else(|_| "certs/server.key".to_string())
    }
    fn ca_path() -> String {
        std::env::var("NEURALBASE_TLS_CA_CERT").unwrap_or_else(|_| "certs/ca.crt".to_string())
    }

    fn build_root_store() -> std::io::Result<RootCertStore> {
        let ca_certs = crate::tls::load_certs(&ca_path())?;
        let mut root_store = RootCertStore::empty();
        for cert in ca_certs {
            root_store
                .add(cert)
                .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))?;
        }
        Ok(root_store)
    }

    /// Build a Raft server-side TLS acceptor with mutual authentication.
    ///
    /// Clients (other Raft nodes) must present a certificate signed by the
    /// cluster CA.
    pub fn build_raft_acceptor() -> std::io::Result<TlsAcceptor> {
        let _ = rustls::crypto::ring::default_provider().install_default();
        let certs = crate::tls::load_certs(&cert_path())?;
        let key = crate::tls::load_key(&key_path())?;
        let root_store = build_root_store()?;

        let client_verifier = rustls::server::WebPkiClientVerifier::builder(Arc::new(root_store))
            .build()
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))?;

        let config = ServerConfig::builder()
            .with_client_cert_verifier(client_verifier)
            .with_single_cert(certs, key)
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))?;

        Ok(TlsAcceptor::from(Arc::new(config)))
    }

    /// Build a Raft client-side TLS connector with mutual authentication.
    ///
    /// Returns `(TlsConnector, ServerName)` — use `connector.connect(name, tcp)`.
    /// `ServerName` defaults to "neuralbase-node"; override via
    /// `NEURALBASE_TLS_SERVER_NAME` env var.
    pub fn build_raft_connector() -> std::io::Result<(TlsConnector, ServerName<'static>)> {
        let _ = rustls::crypto::ring::default_provider().install_default();
        let certs = crate::tls::load_certs(&cert_path())?;
        let key = crate::tls::load_key(&key_path())?;
        let root_store = build_root_store()?;

        let config = ClientConfig::builder()
            .with_root_certificates(root_store)
            .with_client_auth_cert(certs, key)
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))?;

        let name_str = std::env::var("NEURALBASE_TLS_SERVER_NAME")
            .unwrap_or_else(|_| "neuralbase-node".to_string());
        let server_name = ServerName::try_from(name_str)
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))?;

        Ok((TlsConnector::from(Arc::new(config)), server_name))
    }
}
